apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: portfolio
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    redirectUris:
      - https://portfolio-datavirt.apps.vmahabal.dev.datahub.redhat.com
    clientId: portfolio
    secret: changeit
    clientAuthenticatorType: client-secret
    publicClient: true
    directAccessGrantsEnabled: true
